spring:
  application:
    name: batch-consumer-2
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-0:9092,kafka-1:9092,kafka-2:9092} # Provide a default value
    topic: my-topic
    group:
      batch: batch-consumer-group-2